DROP TABLE refresh_tokens;
DROP TABLE exchanges;
DROP TABLE university_follows;
DROP TABLE user_follows;
DROP TABLE university_reviews_reaction_counts;
DROP TABLE university_review_reactions;
DROP TABLE university_reviews;
DROP TABLE user_roles;
DROP TABLE user_notifications;
DROP TABLE user_descriptions;
DROP TABLE user_credentials;
DROP TABLE users;
DROP TABLE user_statuses;
DROP TABLE fields_of_study;
DROP TABLE universities;
DROP TABLE cities;
DROP TABLE countries;
DROP TYPE reaction_type;
DROP TYPE role;
DROP INDEX IF EXISTS idx_cities_country_id;
DROP INDEX IF EXISTS idx_universities_city_id;
DROP INDEX IF EXISTS idx_universities_original_name_trgm;
DROP INDEX IF EXISTS idx_universities_english_name_trgm;
DROP INDEX IF EXISTS idx_users_nick;
DROP INDEX IF EXISTS idx_user_notifications_mail;
DROP INDEX IF EXISTS idx_user_credentials;
DROP INDEX IF EXISTS idx_university_reviews_author_id;
DROP INDEX IF EXISTS idx_university_reviews_university_id;
DROP INDEX IF EXISTS idx_university_reviews_reaction_counts_university_review_id;
DROP INDEX IF EXISTS idx_exchanges_started_at;
DROP INDEX IF EXISTS idx_exchanges_end_at;
DROP INDEX IF EXISTS idx_exchanges_field_of_study_id;
DROP INDEX IF EXISTS idx_exchanges_university_id;
DROP EXTENSION IF EXISTS pg_trgm;