export type ApiErrorResponseCode =
  | 'ResourceNotFound'
  | 'ReferencedResourceNotFound'
  | 'DeletePermissionDenied'
  | 'AuthenticationFailed'
  | 'InvalidToken'
  | 'LoginAlreadyTaken'
  | 'MailAlreadyTaken'
  | 'InvalidRequestBody'
  | 'ResourceAlreadyExists'
  | 'InternalError'
  | 'Size'